package example.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 3.4.0
 * 2020-10-03T13:28:25.829+03:30
 * Generated source version: 3.4.0
 *
 */
@WebService(targetNamespace = "http://example/", name = "hello")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface Hello {

    @WebMethod
    @Action(input = "http://example/hello/bonjourRequest", output = "http://example/hello/bonjourResponse")
    @WebResult(name = "return", targetNamespace = "http://example/", partName = "return")
    public java.lang.String bonjour(

        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    );
}
